### ISSUE TITLE
Design Docs - Backend Routes

### ISSUE THREAD

**Issue by huangs2022672** [keginzburg/webflix#4]
Great job Kyle!

# Backend Routes
​
- [x]  Contains the following sections: HTML, API Endpoints(Backend)
- [x]  Each route has a description
- [x]  API Endpoint routes contains wildcard variables written in `snake_case`
- [x]  Routes does not contain superfluous routes
- [x]  Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    -  i.e. probably don't need a `GET likes` api endpoint because that info comes through the post show
​
### Comments

* have you thought about fetching a user's profiles along with users?
  * GET /api/profiles will get an index of all profiles
  * for POST /api/profiles, think about how the profile will get access to user_id

* if genres exists in a separate table, you'd want to grab them through video's associations

* would likes and mylist be associated with users or profiles?
* you might want a mylist index to show the movies under mylist of a profile/user

* in general think about grabbing data from the backend via associations, and add it to the description for that route. i.e. when you GET /api/videos, you'd want to see if the user/profile has already liked the video

**Comment by keginzburg** [comment]
Hey Sammy!

I've added some edits here as well:

1. I've updated my profile backend routes and nested the GET /api/profiles and POST /api/profiles under users/:id, so I would only be fetching the profiles for a specific user once they log in and create a new profile for a specific user (and have access to their user_id).

2. I've changed my routes so I can access genre through video associations, but is there no benefit to having a GET route for my genres table? I'm having trouble understanding how I will populate my homepage with my placeholder genre/categories without that kind of route. 

3. I've specified that likes and mylists are associated with profiles and added nested routes.

4. I've added a GET /mylists route nested under profiles/:id to find all of the videos mylisted by the current profile.

5. Also, as of now, I've added a note that I will be accessing likes through a videos association and these will be filtered depending on the currently logged in user/profile.

**Comment by huangs2022672** [comment]
Great Job Kyle! 
Now that we are keeping a genre table in the DB, I think it's fine to have a GET /genres. One concern might be that if you have a list of genres, but no movies in that a particular genre, it might show up as a category with no movies.

without using a GET /genres you could potentially set the categories statically at first, or when you fetch all videos you grab the genre out from them into a different part of state.

it's subjective and really up to you which way you want to go about it. Initially I was thinking that we might be dropping the genres table

**Comment by keginzburg** [comment]
Thanks for the note! I'll definitely make that a priority when seeding my database so that genres are represented equally.
